echo "This file related to the java content..."
echo "Iam sairaviteja iam presently using the vim editor..."
echo "welcome to my shellecript..."
echo "Iam updating the shellscript again.."
echo "Iam developing the script file again iam updating the file related to the java content...."
echo "Iam updating the file in the development branch..."
