echo "Hello everyone"
echo "This file related to the shellscript.."
echo "iam sairaviteja "
echo "Iam using the vim editor right now.."
echo "Welcome to my shellscript "
echo "iam updating the file related to the shellscript in the stage branch.."
echo "iam updating the file related to the content shellscripting in the master branch..."
